name=EC1101S Rotary Encoder
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=A high-performance library for EC1101S rotary encoders with debounce support.
paragraph=This library provides a robust and easy-to-use API for interfacing with EC1101S rotary encoders. It handles incremental rotation tracking, boundary limits (min/max), and button state management. Designed for efficiency, it minimizes overhead in the main loop and is suitable for menu navigation, volume control, and industrial UI applications in Arduino or PlatformIO environments.
category=Signal Input
url=https://github.com/Boardoza/Boardoza_Rotary_Encoder_ARGB_Control_Breakout_Board
architectures=*